"""Reference metadata templates for GAEZ crops, scenarios, and code mappings."""
# dimension_profile values:
#   "historical_only"   -> periods HP8100, HP0120; climate AGERA5; no SSP
#   "historical+future" -> all 6 periods; historical=AGERA5, future=CMIP6 GCMs;
#                          SSPs: SSP126, SSP370, SSP585
#   "static"            -> no time dimension
# ══════════════════════════════════════════════════════════════════════

LICENSE = "CC-BY-4.0"


# ──────────────────────────────────────────────────────────────────────
# 1. METADATA_TEMPLATES — one entry per raster layer
# ──────────────────────────────────────────────────────────────────────

METADATA_TEMPLATES = {

    # ── Suitability ──────────────────────────────────────────────────

    "RES05-SIX30AS": {
        "title": "Crop suitability, class index",
        "description": "Crop suitability results presented as an index, calculated for all land area and classified into categories, at approximately 1 km resolution. The crop suitability index represents the weighted sum of extents in different suitability classes, expressing the suitability make up of a grid cell as a number in the range of 0 to 100. The index results in a value of 100 when all land in a location is assessed as very suitable and 0 when all land is not suitable. Estimations account for rain-fed and irrigated conditions, different time periods, and two levels of inputs and management (high and low). Results cover more than 70 major crops including traditional and adapted crops in alignment with VACS, and all soil groups identified in HWSD v2. Results for irrigated cultivation are limited to grid cells where existing cropland is indicated in the GAEZ v5 land cover inventory for 2020. Historical data only at 1 km resolution.",
        "unit": "Class",
        "nodata": 0,
        "scale_factor": 1.0,
        "resolution": "1km",
        "theme": "Suitability and Attainable Yield",
        "sub_theme": "Suitability Class",
        "variable_name": "Crop suitability index in classes; all land in grid cell",
        "dimension_profile": "historical_only",
        "category": "suitability",
        "publication_date": "2025-04-07",
        "classes": {
            1: "SI > 85: Very high",
            2: "SI > 70: High",
            3: "SI > 55: Good",
            4: "SI > 40: Medium",
            5: "SI > 25: Moderate",
            6: "SI > 10: Marginal",
            7: "SI > 0: Very marginal",
            8: "Not suitable",
            9: "Water",
        },
    },
    "RES05-SCX30AS": {
        "title": "Crop suitability for current cropland, class index",
        "description": "Crop suitability results for current cropland presented as an index and classified into categories, at approximately 1 km resolution. Estimations account for rain-fed and irrigated conditions, different time periods, and two levels of inputs and management (high and low). Results cover more than 70 major crops including traditional and adapted crops in alignment with VACS, and all soil groups identified in HWSD v2, covering all land where the high-resolution land cover inventory for 2020 indicates occurrence of some cropland. The assessment assumes that crop cultivation in a grid cell will first occupy the available land with better rated soil and terrain conditions. Results of suitability classes, starting from best to worst, which are sufficient in extent to encompass the indicated cropland share are then averaged to define the map contents.",
        "unit": "Class",
        "nodata": 0,
        "scale_factor": 1.0,
        "resolution": "1km",
        "theme": "Suitability and Attainable Yield",
        "sub_theme": "Suitability Class",
        "variable_name": "Crop suitability index in classes; current cropland in grid cell",
        "dimension_profile": "historical+future",
        "category": "suitability",
        "publication_date": "2025-04-07",
        "classes": {
            1: "SI > 85: Very high",
            2: "SI > 70: High",
            3: "SI > 55: Good",
            4: "SI > 40: Medium",
            5: "SI > 25: Moderate",
            6: "SI > 10: Marginal",
            7: "SI > 0: Very marginal",
            8: "Not suitable",
            9: "No cropland",
            10: "Water",
        },
    },
    "RES05-SXX30AS": {
        "title": "Crop suitability, continuous index, all land",
        "description": "Crop suitability results presented as a continuous index, calculated for all land area, with values stretching over the interval of 0 to 10000, at approximately 1 km resolution. Estimations account for rain-fed and irrigated conditions, different time periods, and two levels of inputs and management (high and low). Results cover more than 70 major crops including traditional and adapted crops in alignment with VACS, and all soil groups identified in HWSD v2. Results for irrigated cultivation are limited to grid cells where existing cropland is indicated in the GAEZ v5 land cover inventory for 2020.",
        "unit": "Index",
        "nodata": -9,
        "scale_factor": 1.0,
        "range": [0, 10000],
        "resolution": "1km",
        "theme": "Suitability and Attainable Yield",
        "sub_theme": "Suitability Index",
        "variable_name": "Suitability index range (0-10000); all land in grid cell",
        "dimension_profile": "historical+future",
        "category": "suitability",
        "publication_date": "2025-04-07",
    },
    "RES05-SX2": {
        "title": "Crop suitability, share of VS+S+MS land",
        "description": "Crop suitability results presented as a continuous index with values stretching over the interval of 0 to 10000, calculated as share of land classified as Very Suitable, Suitable or Moderately Suitable (VS+S+MS), at approximately 10 km resolution. Estimations account for rain-fed and irrigated conditions, and two levels of input management (high and low). Results cover 52 major crops and all soil groups identified in HWSD v2.",
        "unit": "Index",
        "nodata": -9,
        "scale_factor": 1.0,
        "range": [0, 10000],
        "resolution": "10km",
        "theme": "Suitability and Attainable Yield",
        "sub_theme": "Suitability Index",
        "variable_name": "Share of VS+S+MS land in grid cell (range 0-10000)",
        "dimension_profile": "historical+future",
        "category": "suitability",
        "publication_date": "2025-03-19",
    },

    # ── Yield ────────────────────────────────────────────────────────
    "RES05-YLX30AS": {
        "title": "Agro-ecological attainable yield, output density",
        "description": "Agro-ecological attainable yield results represented as output density (potential production divided by total grid cell area), at approximately 1 km resolution. Accounts for rain-fed and irrigated conditions, and two levels of input management (high and low). Results cover more than 70 major crops including traditional and adapted crops in alignment with VACS, and all soil groups identified in HWSD v2. Results for irrigated cultivation are limited to grid cells where existing cropland is indicated in the GAEZ v5 land cover inventory for 2020.",
        "unit": "kg(DW)/ha",
        "nodata": -9,
        "scale_factor": 1.0,
        "resolution": "1km",
        "theme": "Suitability and Attainable Yield",
        "sub_theme": "Agro-ecological Attainable Yield",
        "variable_name": "Output density (potential production divided by total grid cell area)",
        "dimension_profile": "historical+future",
        "category": "yield",
        "publication_date": "2025-04-07",
        "note": "Dry weight. Sugar beet/cane in kg sugar/ha, oil palm in kg oil/ha, cotton in kg lint/ha. Apply conversion factor for fresh weight comparison.",
    },
    "RES05-YXX": {
        "title": "Agro-ecological attainable yield, average of best occurring suitability class",
        "description": "Agro-ecological attainable yield results represented as the average attainable yield of the best occurring suitability class in a grid cell, at approximately 10 km resolution. Accounts for rain-fed and irrigated conditions, and two levels of input management (high and low). Results cover more than 70 major crops including traditional and adapted crops in alignment with VACS, and all soil groups identified in HWSD v2.",
        "unit": "kg(DW)/ha",
        "nodata": -9,
        "scale_factor": 1.0,
        "resolution": "10km",
        "theme": "Suitability and Attainable Yield",
        "sub_theme": "Agro-ecological Attainable Yield",
        "variable_name": "Average attainable yield of best occurring suitability class in grid cell",
        "dimension_profile": "historical+future",
        "category": "yield",
        "publication_date": "2025-03-25",
        "note": "Dry weight. Sugar beet/cane in kg sugar/ha, oil palm in kg oil/ha, cotton in kg lint/ha. Apply conversion factor for fresh weight comparison.",
    },
    
"""
    "RES05-YCX30AS": {
        "title": "Agro-ecological attainable yield, current cropland",
        "description": "Agro-ecological attainable yield results represent average attainable yield values for current cropland as indicated in the GAEZ v5 land cover inventory for 2020. Estimations account for rain-fed and irrigated conditions, and two levels of input management (high and low). Results cover more than 70 major crops including traditional and adapted crops in alignment with VACS, and all soil groups identified in HWSD v2. Yields represent agro-ecological potential after applying all constraint factors (thermal, moisture, agro-climatic, soil, terrain).",
        "unit": "kg(DW)/ha",
        "nodata": -9,
        "scale_factor": 1.0,
        "resolution": "1km",
        "theme": "Suitability and Attainable Yield",
        "sub_theme": "Agro-ecological Attainable Yield",
        "variable_name": "Average attainable yield of current cropland",
        "dimension_profile": "historical+future",
        "category": "yield",
        "publication_date": "2025-04-07",
        "note": "Dry weight. Sugar beet/cane in kg sugar/ha, oil palm in kg oil/ha, cotton in kg lint/ha. Apply conversion factor for fresh weight comparison.",
    },
"""
    "RES02-YLD": {
        "title": "Agro-climatic potential yield",
        "description": "Agro-climatic potential yield results at approximately 10 km resolution for more than 70 major crops including traditional and adapted crops in alignment with VACS. Accounts for rain-fed and irrigated conditions, and two levels of input management (high and low). Represents yield potential based on climate factors only, before applying soil and terrain constraints. Modeled results for crop sub-types are available only via download from Google Cloud Storage and are not published on the GAEZ v5 platform.",
        "unit": "kg(DW)/ha",
        "nodata": -9,
        "scale_factor": 1.0,
        "resolution": "10km",
        "theme": "Agro-climatic Potential Yield",
        "sub_theme": "Agro-Climatic Yield",
        "variable_name": "Agro-climatic potential yield",
        "dimension_profile": "historical+future",
        "category": "yield",
        "publication_date": "2025-03-27",
        "note": "Dry weight. Sugar beet/cane in kg sugar/ha, oil palm in kg oil/ha, cotton in kg lint/ha. Apply conversion factor for fresh weight comparison.",
    },

    # ── Reality (actual production) ──────────────────────────────────

    "RES06-HAR": {
        "title": "Downscaled harvested area",
        "description": "Harvested area for the year 2020 provided in hectares at approximately 10 km resolution for 38 major crops/crop groups, separately for rain-fed, irrigated or total cropland. Country totals are based on FAOSTAT statistics for the years 2019-2021 (accessed in 2022). For single crops or fairly homogenous crop groups the units are in 1000 ha. For crop groups which include a greater variety of crops (e.g. vegetables, stimulants) international price weights compiled by FAO (constant 2014-2016 I$) were used to aggregate individual items.",
        "unit": "ha",
        "nodata": 0,
        "scale_factor": 1000.0,
        "resolution": "10km",
        "theme": "Actual Yields and Production",
        "sub_theme": "Actual Yields and Production",
        "variable_name": "Harvested area",
        "dimension_profile": "static",
        "category": "reality",
        "reference_year": 2020,
        "statistics_source": "FAOSTAT 2019-2021",
        "publication_date": "2025-05-07",
    },
    "RES06-PRD": {
        "title": "Downscaled production",
        "description": "Production for the year 2020 expressed as tonnes at approximately 10 km resolution for 38 major crops/crop groups, separately for rain-fed, irrigated or total cropland. Country totals are based on FAOSTAT statistics for the years 2019-2021 (accessed in 2022). For single crops or fairly homogenous crop groups the units are in 1000 tonnes. For crop groups which include a greater variety of crops (e.g. vegetables, stimulants) international price weights compiled by FAO (constant 2014-2016 I$) were used to aggregate individual items.",
        "unit": "tonnes",
        "nodata": 0,
        "scale_factor": 1000.0,
        "resolution": "10km",
        "theme": "Actual Yields and Production",
        "sub_theme": "Actual Yields and Production",
        "variable_name": "Production",
        "dimension_profile": "static",
        "category": "reality",
        "reference_year": 2020,
        "statistics_source": "FAOSTAT 2019-2021",
        "publication_date": "2025-05-08",
    },
    "RES06-YLD": {
        "title": "Downscaled yield",
        "description": "Yield for the year 2020 expressed as tonnes/ha at approximately 10 km resolution for 38 major crops/crop groups, separately for rain-fed, irrigated or total cropland. Country totals are based on FAOSTAT statistics for the years 2019-2021 (accessed in 2022). For single crops or fairly homogenous crop groups the units of production are in 1000 tonnes. For crop groups which include a greater variety of crops (e.g. vegetables, stimulants) international price weights compiled by FAO (constant 2014-2016 I$) were used to aggregate individual items.",
        "unit": "tonnes/ha",
        "nodata": 0,
        "scale_factor": 1.0,
        "resolution": "10km",
        "theme": "Actual Yields and Production",
        "sub_theme": "Actual Yields and Production",
        "variable_name": "Yield",
        "dimension_profile": "static",
        "category": "reality",
        "reference_year": 2020,
        "statistics_source": "FAOSTAT 2019-2021",
        "publication_date": "2025-05-07",
    },

    # ── Constraints ──────────────────────────────────────────────────

    "RES02-FC0": {
        "title": "Total climate related crop yield constraint factor",
        "description": "Integrates temperature, soil moisture, and agro-climatic constraint factors into a single total climate constraint factor. Provided at approximately 10 km resolution. Values range from 0 (most limiting) to 1 (no constraint). Modeled results for crop sub-types are available only via download from Google Cloud Storage.",
        "unit": "Index",
        "nodata": -9,
        "scale_factor": 1.0,
        "range": [0, 1],
        "resolution": "10km",
        "theme": "Agro-climatic Potential Yield",
        "sub_theme": "Constraint Factors",
        "variable_name": "Total climate related crop yield constraint factor '0'",
        "dimension_profile": "historical+future",
        "category": "constraints",
        "publication_date": "2025-03-27",
    },
    "RES02-FC1": {
        "title": "Crop yield constraint factor, thermal",
        "description": "Evaluates the impact of temperature-related limitations on crop yield potential. Provided at approximately 10 km resolution. Values range from 0 (most limiting) to 1 (very suitable). Modeled results for crop sub-types are available only via download from Google Cloud Storage.",
        "unit": "Index",
        "nodata": -9,
        "scale_factor": 1.0,
        "range": [0, 1],
        "resolution": "10km",
        "theme": "Agro-climatic Potential Yield",
        "sub_theme": "Constraint Factors",
        "variable_name": "Crop yield constraint factor '1' (thermal)",
        "dimension_profile": "historical+future",
        "category": "constraints",
        "publication_date": "2025-03-27",
    },
    "RES02-FC2": {
        "title": "Crop yield constraint factor, moisture",
        "description": "Assesses the impact of soil moisture availability on crop yield potential. Provided at approximately 10 km resolution. Values range from 0 (most limiting) to 1 (very suitable). Modeled results for crop sub-types are available only via download from Google Cloud Storage.",
        "unit": "Index",
        "nodata": -9,
        "scale_factor": 1.0,
        "range": [0, 1],
        "resolution": "10km",
        "theme": "Agro-climatic Potential Yield",
        "sub_theme": "Constraint Factors",
        "variable_name": "Crop yield constraint factor '2' (moisture)",
        "dimension_profile": "historical+future",
        "category": "constraints",
        "publication_date": "2025-03-27",
    },
    "RES02-FC3": {
        "title": "Crop yield constraint factor, agro-climatic",
        "description": "Assesses climate related impacts affecting production potential through pests and diseases, and unfavorable working conditions in the field. Provided at approximately 10 km resolution. Values range from 0 (most limiting) to 1 (very suitable). Modeled results for crop sub-types are available only via download from Google Cloud Storage.",
        "unit": "Index",
        "nodata": -9,
        "scale_factor": 1.0,
        "range": [0, 1],
        "resolution": "10km",
        "theme": "Agro-climatic Potential Yield",
        "sub_theme": "Constraint Factors",
        "variable_name": "Crop yield constraint factor '3' (agro-climatic)",
        "dimension_profile": "historical+future",
        "category": "constraints",
        "publication_date": "2025-03-27",
    },
    "SQX": {
        "title": "Soil quality index",
        "description": "Soil quality rating for agricultural production at 1 km resolution. Based on HWSD v2.01 soil attributes processed through the GAEZ framework. Evaluates seven soil qualities (SQ1-SQ7) for dominant soils using maize as reference crop. Expressed as normalized rating 0 to 1, where 1 indicates no constraint. Uses multiplicative aggregation of individual soil quality ratings. See SOIL_QUALITIES for factor definitions.",
        "unit": "Index",
        "nodata": 0,
        "scale_factor": 1.0,
        "range": [0, 1],
        "resolution": "1km",
        "theme": "Land and Water Resources",
        "sub_theme": "Soil Resources",
        "variable_name": "Soil Quality",
        "dimension_profile": "static",
        "category": "constraints",
        "publication_date": "2025-09-19",
    },
    "SQ-IDX": {
        "title": "Most limiting soil quality",
        "description": "Identifies the soil quality or terrain factor that imposes the strongest constraint on land suitability at each grid cell. Based on HWSD v2.01 processed through GAEZ framework. Evaluates SQ1-SQ7 for dominant soils using maize as reference crop. Categorical classification where each pixel represents the most limiting factor.",
        "unit": "Class",
        "nodata": 0,
        "scale_factor": 1.0,
        "resolution": "1km",
        "theme": "Land and Water Resources",
        "sub_theme": "Soil Resources",
        "variable_name": "Most Limiting Soil Quality",
        "dimension_profile": "static",
        "category": "constraints",
        "publication_date": "2025-09-19",
        "classes_ref": "SOIL_QUALITIES",
    },

    # ── Moisture ─────────────────────────────────────────────────────

    "RES05-ETL": {
        "title": "Actual crop evapotranspiration",
        "description": "Actual crop evapotranspiration (excluding irrigation) provided in mm as average of grid cell at approximately 10 km resolution. Estimations account for rain-fed and irrigated conditions, and two levels of input management (high and low). Results cover major crops and all soil groups identified in HWSD v2.",
        "unit": "mm",
        "nodata": -9,
        "scale_factor": 1.0,
        "resolution": "10km",
        "theme": "Suitability and Attainable Yield",
        "sub_theme": "Crop Water Indicators",
        "variable_name": "Actual crop evapotranspiration (excluding irrigation), average for grid cell",
        "dimension_profile": "historical+future",
        "category": "moisture",
        "publication_date": "2025-03-19",
    },
    "RES05-WDL": {
        "title": "Water deficit / net irrigation requirement during crop cycle",
        "description": "Water deficit (net irrigation requirement during crop cycle) provided in mm as average of grid cell at approximately 10 km resolution. Indicates the amount of additional water needed beyond rainfall to meet crop water demands during the growing cycle.",
        "unit": "mm",
        "nodata": -9,
        "scale_factor": 1.0,
        "resolution": "10km",
        "theme": "Suitability and Attainable Yield",
        "sub_theme": "Crop Water Indicators",
        "variable_name": "Water deficit/net irrigation requirement during crop cycle, total grid cell",
        "dimension_profile": "historical+future",
        "category": "moisture",
        "publication_date": "2025-03-19",
    },
    "RES01-ET0": {
        "title": "Reference evapotranspiration",
        "description": "Annual reference evapotranspiration calculated using the Penman-Monteith equation with assumed available water capacity of 100 mm/m, at approximately 10 km resolution. Represents the evaporative demand of the atmosphere — the amount of water that would be lost through a well-watered reference crop. Combined with precipitation indicates overall moisture stress level.",
        "unit": "mm",
        "nodata": -9,
        "scale_factor": 1.0,
        "resolution": "10km",
        "theme": "Agro-climatic Resources",
        "sub_theme": "Moisture Regime",
        "variable_name": "Reference evapotranspiration (using AWC=100 mm/m)",
        "dimension_profile": "historical+future",
        "category": "moisture",
        "publication_date": "2025-03-19",
    },
    "RES01-PRC": {
        "title": "Mean annual precipitation",
        "description": "Mean annual precipitation at approximately 10 km resolution. The most fundamental moisture variable for agricultural planning.",
        "unit": "mm",
        "nodata": -9,
        "scale_factor": 1.0,
        "resolution": "10km",
        "theme": "Agro-climatic Resources",
        "sub_theme": "Moisture Regime",
        "variable_name": "Mean annual precipitation (mm)",
        "dimension_profile": "historical+future",
        "category": "moisture",
        "publication_date": "2025-03-18",
    },
    "RES01-RID": {
        "title": "Annual P/PET ratio",
        "description": "Ratio of annual precipitation to reference potential evapotranspiration, expressed as percentage. A value of 100% means precipitation matches evaporative demand. Values below 100% indicate water deficit; values above 100% mean precipitation exceeds demand. Provides a single-number summary of annual moisture balance at each location.",
        "unit": "%",
        "nodata": -9,
        "scale_factor": 1.0,
        "resolution": "10km",
        "theme": "Agro-climatic Resources",
        "sub_theme": "Moisture Regime",
        "variable_name": "Annual P/PET ratio (*100)",
        "dimension_profile": "historical+future",
        "category": "moisture",
        "publication_date": "2025-03-19",
    },
    "RES01-RIW": {
        "title": "Seasonal P/PET ratio, winter period",
        "description": "Ratio of precipitation to potential evapotranspiration during the winter half-year (October-March in northern hemisphere), expressed as percentage. For Tunisia and Mediterranean climates, winter is the primary rainy season and main growing period for most crops. This ratio indicates how well winter rainfall meets crop water demands.",
        "unit": "%",
        "nodata": -9,
        "scale_factor": 1.0,
        "resolution": "10km",
        "theme": "Agro-climatic Resources",
        "sub_theme": "Moisture Regime",
        "variable_name": "Seasonal P/PET ratio (*100) in winter (October-March in northern hemisphere)",
        "dimension_profile": "historical+future",
        "category": "moisture",
        "publication_date": "2025-03-18",
    },
    "RES01-RIS": {
        "title": "Seasonal P/PET ratio, summer period",
        "description": "Ratio of precipitation to potential evapotranspiration during the summer half-year (April-September in northern hemisphere), expressed as percentage. For Tunisia, summer is typically very dry with near-zero values in southern regions, indicating that summer cropping requires irrigation.",
        "unit": "%",
        "nodata": -9,
        "scale_factor": 1.0,
        "resolution": "10km",
        "theme": "Agro-climatic Resources",
        "sub_theme": "Moisture Regime",
        "variable_name": "Seasonal P/PET ratio (*100) in summer (April-September in northern hemisphere)",
        "dimension_profile": "historical+future",
        "category": "moisture",
        "publication_date": "2025-03-18",
    },

    # ── Climate ──────────────────────────────────────────────────────

    "RES01-MCL": {
        "title": "Thermal climates",
        "description": "Major latitudinal climatic zones based on monthly temperatures reduced to sea level. Classifies locations into 12 thermal climate types based on temperature seasonality and rainfall patterns. Used for crop presence screening to determine which crops are climatically feasible at a location.",
        "unit": "class",
        "nodata": 0,
        "scale_factor": 1.0,
        "resolution": "10km",
        "theme": "Agro-climatic Resources",
        "sub_theme": "Climate Classification",
        "variable_name": "Thermal Climates (temperatures reduced to sea level)",
        "dimension_profile": "historical+future",
        "category": "climate",
        "publication_date": "2025-03-18",
        "classes": {
            1: "Tropics lowland",
            2: "Tropics highland",
            3: "Subtropics summer rainfall",
            4: "Subtropics winter rainfall",
            5: "Subtropics low rainfall",
            6: "Temperate oceanic",
            7: "Temperate sub-continental",
            8: "Temperate continental",
            9: "Boreal oceanic",
            10: "Boreal sub-continental",
            11: "Boreal continental",
            12: "Arctic",
        },
    },
    "RES01-MC2": {
        "title": "Thermal zones",
        "description": "Classification of actual temperature regimes into 12 thermal zone classes. Reflects actual monthly temperature conditions throughout the year, used for fallow period requirements and crop-specific temperature suitability assessment.",
        "unit": "class",
        "nodata": 0,
        "scale_factor": 1.0,
        "resolution": "10km",
        "theme": "Agro-climatic Resources",
        "sub_theme": "Climate Classification",
        "variable_name": "Thermal Zones",
        "dimension_profile": "historical+future",
        "category": "climate",
        "publication_date": "2025-03-18",
        "classes": {
            1: "Tropics warm",
            2: "Tropics cool/cold/very cold",
            3: "Subtropics warm/moderately cool",
            4: "Subtropics cool",
            5: "Subtropics cold",
            6: "Subtropics very cold",
            7: "Temperate cool",
            8: "Temperate cold",
            9: "Temperate very cold",
            10: "Boreal cold",
            11: "Boreal very cold",
            12: "Arctic",
        },
    },

    # ── Season ───────────────────────────────────────────────────────

    "RES01-LGP": {
        "title": "Total number of growing period days, classified",
        "description": "Length of growing period expressed in classes at approximately 10 km resolution. Growing period is defined as days when both temperature and moisture conditions permit crop growth. Classified into 16 interval classes from 0 days to 365+ days.",
        "unit": "class",
        "nodata": 0,
        "scale_factor": 1.0,
        "resolution": "10km",
        "theme": "Agro-climatic Resources",
        "sub_theme": "Climate Classification",
        "variable_name": "Total number of growing period days class",
        "dimension_profile": "historical+future",
        "category": "season",
        "publication_date": "2025-03-18",
        "classes": {
            1: "0 days",
            2: "1-29 days",
            3: "30-59 days",
            4: "60-89 days",
            5: "90-119 days",
            6: "120-149 days",
            7: "150-179 days",
            8: "180-209 days",
            9: "210-239 days",
            10: "240-269 days",
            11: "270-299 days",
            12: "300-329 days",
            13: "330-364 days",
            14: "365- days",
            15: "365 days",
            16: "365+ days",
        },
    },
    "RES01-LGD": {
        "title": "Total number of growing period days",
        "description": "Total number of days during the year when both temperature and moisture conditions are conducive to crop growth, provided as a continuous value in days at approximately 10 km resolution. This is the sum of all growing period components, which may include multiple separate growing windows within a year.",
        "unit": "days",
        "nodata": -9,
        "scale_factor": 1.0,
        "resolution": "10km",
        "theme": "Agro-climatic Resources",
        "sub_theme": "Growing Period",
        "variable_name": "Total number of growing period days",
        "dimension_profile": "historical+future",
        "category": "season",
        "publication_date": "2025-03-18",
    },
    "RES01-LD1": {
        "title": "Length of longest component LGP",
        "description": "Length in days of the longest continuous growing period component. In locations with split growing seasons (e.g. bimodal rainfall), the total LGP may comprise multiple separate windows. This value identifies the longest uninterrupted window, which determines the maximum crop cycle length that can be accommodated without supplemental irrigation.",
        "unit": "days",
        "nodata": -9,
        "scale_factor": 1.0,
        "resolution": "10km",
        "theme": "Agro-climatic Resources",
        "sub_theme": "Growing Period",
        "variable_name": "Length of longest component LGP (days)",
        "dimension_profile": "historical+future",
        "category": "season",
        "publication_date": "2025-03-18",
    },
    "RES01-LGB": {
        "title": "Beginning date of longest component LGP",
        "description": "Julian day of year when the longest continuous growing period component begins. Combined with LD1, defines the main planting window: start date and duration of the best uninterrupted growing opportunity at each location.",
        "unit": "day of year",
        "nodata": -9,
        "scale_factor": 1.0,
        "range": [1, 365],
        "resolution": "10km",
        "theme": "Agro-climatic Resources",
        "sub_theme": "Growing Period",
        "variable_name": "Beginning date of longest component LGP (day-of-year)",
        "dimension_profile": "historical+future",
        "category": "season",
        "publication_date": "2025-03-18",
    },
    "RES01-NDD": {
        "title": "Longest consecutive dry days in temperature growing period",
        "description": "Longest period of consecutive dry days occurring within the temperature growing period (LGPt=5, days with Ta>5C) at approximately 10 km resolution. Indicates the maximum drought stress duration a crop may face during the season. Critical for selecting drought-tolerant varieties and planning irrigation scheduling.",
        "unit": "days",
        "nodata": -9,
        "scale_factor": 1.0,
        "resolution": "10km",
        "theme": "Agro-climatic Resources",
        "sub_theme": "Growing Period",
        "variable_name": "Longest period of consecutive dry days in temperature growing period LGPt=5 (days)",
        "dimension_profile": "historical+future",
        "category": "season",
        "publication_date": "2025-03-18",
    },

    # ── Calendar ─────────────────────────────────────────────────────

    "RES02-CBD": {
        "title": "Beginning of crop growth cycle",
        "description": "Optimum starting day of crop growth cycle provided as day of year at approximately 10 km resolution. Represents the Julian day when the crop cycle should begin for maximum yield potential. Modeled results for crop sub-types are available only via download from Google Cloud Storage.",
        "unit": "day of year",
        "nodata": -9,
        "scale_factor": 1.0,
        "range": [1, 365],
        "resolution": "10km",
        "theme": "Agro-climatic Potential Yield",
        "sub_theme": "Growth Cycle Attributes",
        "variable_name": "Beginning of crop growth cycle (day)",
        "dimension_profile": "historical+future",
        "category": "calendar",
        "publication_date": "2025-03-27",
    },
    "RES02-CYL": {
        "title": "Length of crop growth cycle",
        "description": "Length of the optimum crop growth cycle provided in days at approximately 10 km resolution. Represents the number of days from planting to harvest for maximum yield potential. Modeled results for crop sub-types are available only via download from Google Cloud Storage.",
        "unit": "days",
        "nodata": -9,
        "scale_factor": 1.0,
        "resolution": "10km",
        "theme": "Agro-climatic Potential Yield",
        "sub_theme": "Growth Cycle Attributes",
        "variable_name": "Length of crop growth cycle (days)",
        "dimension_profile": "historical+future",
        "category": "calendar",
        "publication_date": "2025-03-27",
    },
    "RES02-ETA": {
        "title": "Crop-specific actual evapotranspiration",
        "description": "Crop-specific actual evapotranspiration provided in mm at approximately 10 km resolution. Represents the actual water lost through evaporation and plant transpiration during the crop growth cycle. Modeled results for crop sub-types are available only via download from Google Cloud Storage.",
        "unit": "mm",
        "nodata": -9,
        "scale_factor": 1.0,
        "resolution": "10km",
        "theme": "Agro-climatic Potential Yield",
        "sub_theme": "Growth Cycle Attributes",
        "variable_name": "Crop-specific actual evapotranspiration (mm)",
        "dimension_profile": "historical+future",
        "category": "calendar",
        "publication_date": "2025-03-27",
    },
    "RES02-TSC": {
        "title": "Crop-specific accumulated temperature during growth cycle",
        "description": "Crop-specific accumulated temperature sums during the crop growth cycle at approximately 10 km resolution. Represents the total heat units accumulated during the growing season, used for matching crop heat requirements. Modeled results for crop sub-types are available only via download from Google Cloud Storage.",
        "unit": "degC*days",
        "nodata": -9999,
        "scale_factor": 1.0,
        "resolution": "10km",
        "theme": "Agro-climatic Potential Yield",
        "sub_theme": "Growth Cycle Attributes",
        "variable_name": "Crop-specific accumulated temperature during crop growth cycle",
        "dimension_profile": "historical+future",
        "category": "calendar",
        "publication_date": "2025-04-01",
    },
    "RES02-WDE": {
        "title": "Crop water deficit",
        "description": "Crop water deficit provided in mm at approximately 10 km resolution. Represents the difference between crop water requirement and actual water available during the growth cycle, indicating the amount of supplemental irrigation needed.",
        "unit": "mm",
        "nodata": -9,
        "scale_factor": 1.0,
        "resolution": "10km",
        "theme": "Agro-climatic Potential Yield",
        "sub_theme": "Growth Cycle Attributes",
        "variable_name": "Crop water deficit (mm)",
        "dimension_profile": "historical+future",
        "category": "calendar",
        "publication_date": "2025-03-27",
    },

    # ── Intensification ──────────────────────────────────────────────

    "RES01-MCR": {
        "title": "Multi-cropping class, rain-fed",
        "description": "Classification of sequential multi-cropping zones under rain-fed conditions. Indicates potential for cultivating multiple crops per year based on growing period length, temperature requirements, and moisture availability without irrigation.",
        "unit": "class",
        "nodata": 255,
        "scale_factor": 1.0,
        "resolution": "10km",
        "theme": "Agro-climatic Resources",
        "sub_theme": "Climate Classification",
        "variable_name": "Multi-cropping class (rain-fed)",
        "dimension_profile": "historical+future",
        "category": "intensification",
        "publication_date": "2025-03-18",
        "classes": {
            1: "No cropping",
            2: "Single cropping",
            3: "Limited double cropping",
            4: "Double cropping",
            5: "Double cropping with rice",
            6: "Double rice cropping",
            7: "Triple cropping",
            8: "Triple rice cropping",
        },
    },
    "RES01-MCI": {
        "title": "Multi-cropping class, irrigated",
        "description": "Classification of sequential multi-cropping zones under irrigated conditions. Indicates potential for cultivating multiple crops per year when irrigation water is available, based on temperature requirements and accumulated temperature sums.",
        "unit": "class",
        "nodata": 255,
        "scale_factor": 1.0,
        "resolution": "10km",
        "theme": "Agro-climatic Resources",
        "sub_theme": "Climate Classification",
        "variable_name": "Multi-cropping class (with irrigation)",
        "dimension_profile": "historical+future",
        "category": "intensification",
        "publication_date": "2025-03-18",
        "classes": {
            1: "No cropping",
            2: "Single cropping",
            3: "Limited double cropping",
            4: "Double cropping",
            5: "Double cropping with rice",
            6: "Double rice cropping",
            7: "Triple cropping",
            8: "Triple rice cropping",
        },
    },

    # ── Terrain ──────────────────────────────────────────────────────

    "AEZ57": {
        "title": "AEZ classification, 57 classes",
        "description": "Agro-ecological Zones classification combining spatial layers of thermal and moisture regimes with broad categories of soil/terrain qualities. Indicates locations with irrigated soils and land with severely limiting bio-physical constraints including very cold, very dry, very steep terrain or very poor soil/terrain conditions.",
        "unit": "class",
        "nodata": 255,
        "scale_factor": 1.0,
        "resolution": "1km",
        "theme": "Land and Water Resources",
        "sub_theme": "Agro-ecological Zones",
        "variable_name": "AEZ Classification (57 classes)",
        "dimension_profile": "static",
        "fixed_period": "HP0120",
        "category": "terrain",
        "publication_date": "2025-03-03",
    },
    "SLOPE-MED": {
        "title": "Median slope class",
        "description": "Terrain slope information compiled from ALOS World 3D-30m (AW3D30) elevation data provided by JAXA. Slopes calculated at 30 arc-seconds and grouped into ten gradient classes.",
        "unit": "class",
        "nodata": None,
        "scale_factor": 1.0,
        "resolution": "1km",
        "theme": "Land and Water Resources",
        "sub_theme": "Terrain Resources",
        "variable_name": "Median Slope Class",
        "dimension_profile": "static",
        "category": "terrain",
        "publication_date": "2024-12-16",
        "classes": {
            1: "0.0-0.5%",
            2: "0.5-2%",
            3: "2-5%",
            4: "5-8%",
            5: "8-12%",
            6: "12-16%",
            7: "16-24%",
            8: "24-30%",
            9: "30-45%",
            10: ">45%",
        },
    },
    "LR-IRR": {
        "title": "Share of irrigated land",
        "description": "Percentage of cropland area under irrigation in each grid cell. Derived from the Global Area Equipped for Irrigation Dataset using sub-national irrigation statistics covering 17298 administrative units from various official sources for years 2000, 2005, 2010, and 2015.",
        "unit": "%",
        "nodata": None,
        "scale_factor": 1.0,
        "range": [0, 100],
        "resolution": "1km",
        "theme": "Land and Water Resources",
        "sub_theme": "Water Resources",
        "variable_name": "Share of Irrigated Land",
        "dimension_profile": "static",
        "category": "terrain",
        "publication_date": "2025-03-17",
    },
}


# ──────────────────────────────────────────────────────────────────────
# 2. DATASET_CATEGORIES — category descriptions only, no per-dataset text
# ──────────────────────────────────────────────────────────────────────
# Per-dataset info lives in METADATA_TEMPLATES. Use:
#   [k for k, v in METADATA_TEMPLATES.items() if v["category"] == "suitability"]
# to get all map_codes in a category.

DATASET_CATEGORIES = {
    "suitability": "Ranks crops for a given location. Core output of the app — the direct answer to 'what should I grow here.' All four datasets are different representations of the same underlying suitability assessment: class vs continuous, all land vs cropland only.",
    "yield": "Answers 'how much can I expect to harvest.' Attainable yield includes soil and terrain constraints (realistic number). Potential yield is climate-only ceiling (theoretical maximum). The gap between them quantifies how much soil improvement could gain.",
    "reality": "What farmers actually grow and harvest in a region. Grounds recommendations in real-world practice. Lets you compute yield gaps (actual vs attainable) and show the user what their neighbors are doing.",
    "constraints": "Decomposes suitability into component factors to explain why a crop scores well or poorly. Each factor isolates one dimension — temperature, moisture, pests, soil quality, soil bottleneck. Turns a score into an explanation and drives improvement advice.",
    "climate": "Classifies the thermal regime at a location. First-pass filter in the pipeline: if the climate type doesn't match the crop's requirements, skip it immediately. Eliminates impossible crops before touching expensive per-crop rasters.",
    "moisture": "Full water picture: how much rain falls, how much evaporates, whether the balance is surplus or deficit by season. Determines whether rain-fed cropping works or irrigation is needed, and quantifies the water gap.",
    "season": "Temporal boundaries of agriculture at a location: how many days available for growing, how long the best uninterrupted stretch is, when it starts, and the worst drought gap within it. Determines which crop cycle lengths are feasible.",
    "calendar": "Crop-specific timing and resource use during the growth cycle. Generates actual planting and harvest dates, heat requirements, and per-crop water demand. Turns a recommendation into a farming plan.",
    "intensification": "Whether the location supports more than one crop per year. Rain-fed and irrigated are separate because irrigation can unlock a second or third cycle that rainfall alone cannot support.",
    "terrain": "Physical reality of the site that doesn't change with crop choice. Agro-ecological zone gives a composite biophysical classification. Slope determines mechanization feasibility. Irrigation infrastructure tells you whether irrigated options are realistic.",
}


# ──────────────────────────────────────────────────────────────────────
# 3. CROP_REGISTRY — canonical crops with codes per source
# ──────────────────────────────────────────────────────────────────────
# No standalone entries for subtypes that already exist under a parent.

CROP_REGISTRY = {
    "alfalfa": {
        "caption": "Alfalfa",
        "codes": {"RES02": "ALFA", "RES05": "ALF"},
    },
    "avocado": {
        "caption": "Avocado",
        "codes": {"RES02": "AVOC", "RES05": "AVOC"},
        "subtypes": {
            "subtropical": {"codes": {"RES02": "AVOCST", "RES05": "AVOST"}, "description": "Subtropical ecotype"},
            "tropical_highland": {"codes": {"RES02": "AVOCTH", "RES05": "AVOTH"}, "description": "Tropical highland"},
            "tropical_lowland": {"codes": {"RES02": "AVOCTL", "RES05": "AVOTL"}, "description": "Tropical lowland"},
        },
        "description": "Best of subtropical, tropical highland, and tropical lowland ecotypes",
    },
    "banana": {
        "caption": "Banana and plantain",
        "codes": {"RES02": "BANA", "RES05": "BAN", "RES06": "BAN", "RES07": "BAN"},
    },
    "barley": {
        "caption": "Barley",
        "codes": {"RES02": "BARL", "RES05": "BRL", "RES06": "BRL", "RES07": "BRL"},
        "subtypes": {
            "spring": {"codes": {"RES02": "SBRL"}, "description": "Spring barley"},
            "winter": {"codes": {"RES02": "WBRL"}, "description": "Winter barley (sub-tropical and tropical highland)"},
            "highland": {"codes": {"RES02": "HBRL"}, "description": "Highland barley (tropics)"},
            "temperate": {"codes": {"RES02": "TBRL"}, "description": "Temperate/sub-tropical barley"},
        },
        "description": "Best of all barley types",
    },
    "biomass_sorghum": {
        "caption": "Biomass sorghum",
        "codes": {"RES02": "BSRG", "RES05": "BSG"},
        "subtypes": {
            "highland": {"codes": {"RES02": "BHSG"}, "description": "Highland"},
            "lowland": {"codes": {"RES02": "BLSG"}, "description": "Lowland"},
            "temperate": {"codes": {"RES02": "BTSG"}, "description": "Temperate"},
        },
        "description": "Best of highland, lowland, and temperate types",
    },
    "brachiaria": {"caption": "Brachiaria", "codes": {"RES02": "BRCH", "RES05": "BCH"}},
    "buckwheat": {"caption": "Buckwheat", "codes": {"RES02": "BCKW", "RES05": "BCK"}},
    "cabbage": {"caption": "Cabbage", "codes": {"RES02": "CABB", "RES05": "CAB"}},
    "cacao": {
        "caption": "Cacao",
        "codes": {"RES02": "COCO", "RES05": "COC", "RES06": "COC"},
        "subtypes": {
            "comum": {"codes": {"RES02": "COCC"}, "description": "Comum variety"},
            "hybrid": {"codes": {"RES02": "COCH"}, "description": "Hybrid variety"},
        },
        "description": "Best of comum and hybrid varieties",
    },
    "camelina": {
        "caption": "Camelina",
        "codes": {"RES02": "CAME", "RES05": "CAM"},
        "subtypes": {
            "autumn_winter": {"codes": {"RES02": "CAMW"}, "description": "Autumn and winter types"},
            "spring": {"codes": {"RES02": "CAMSP"}, "description": "Spring types"},
        },
        "description": "Best of all types",
    },
    "carinata": {
        "caption": "Carinata",
        "codes": {"RES02": "CARI", "RES05": "CRT"},
        "subtypes": {
            "spring": {"codes": {"RES02": "CARIS"}, "description": "Spring types"},
            "winter": {"codes": {"RES02": "CARIW"}, "description": "Winter type"},
        },
        "description": "Best of spring and winter types",
    },
    "carrot": {"caption": "Carrot", "codes": {"RES02": "CARR", "RES05": "CAR"}},
    "cashew": {"caption": "Cashew", "codes": {"RES02": "CASH", "RES05": "CSH"}},
    "cassava": {"caption": "Cassava", "codes": {"RES02": "CASV", "RES05": "CSV", "RES06": "CSV", "RES07": "CSV"}},
    "castor_bean": {"caption": "Castor bean", "codes": {"RES02": "CAST", "RES05": "CST"}},
    "chickpea": {"caption": "Chickpea", "codes": {"RES02": "CHCK", "RES05": "CHK"}},
    "citrus": {"caption": "Citrus", "codes": {"RES02": "CITR", "RES05": "CIT"}},
    "coconut": {
        "caption": "Coconut",
        "codes": {"RES02": "COCN", "RES05": "CON", "RES06": "CON"},
        "subtypes": {
            "tall": {"codes": {"RES02": "COC1"}, "description": "Tall coconut"},
            "hybrid": {"codes": {"RES02": "COC2"}, "description": "Hybrid coconut"},
            "dwarf": {"codes": {"RES02": "COC3"}, "description": "Dwarf coconut"},
        },
        "description": "Best of tall, hybrid, and dwarf types",
    },
    "coffee": {
        "caption": "Coffee",
        "codes": {"RES02": "COFF", "RES05": "COF", "RES06": "COF"},
        "subtypes": {
            "arabica": {"codes": {"RES02": "COFA"}, "description": "Coffee arabica"},
            "robusta": {"codes": {"RES02": "COFR"}, "description": "Coffee robusta"},
        },
        "description": "Best of arabica and robusta",
    },
    "cotton": {"caption": "Cotton", "codes": {"RES02": "COTT", "RES05": "COT", "RES06": "COT", "RES07": "COT"}, "description": "RES06/RES07 report as seed cotton"},
    "cowpea": {"caption": "Cowpea", "codes": {"RES02": "COWP", "RES05": "COW"}},
    "dry_pea": {"caption": "Dry pea", "codes": {"RES02": "DPEA", "RES05": "PEA"}},
    "dryland_rice": {"caption": "Dryland rice", "codes": {"RES02": "RICD", "RES05": "RCD"}},
    "energy_cane": {
        "caption": "Energy cane",
        "codes": {"RES02": "ECAN", "RES05": "ECN"},
        "subtypes": {
            "vertix2": {"codes": {"RES02": "ECANV2", "RES05": "EC2"}, "description": "Type Vertix 2 (developed by GranBio)"},
            "vertix3": {"codes": {"RES02": "ECANV3", "RES05": "EC3"}, "description": "Type Vertix 3 (developed by GranBio)"},
        },
        "description": "Best of Vertix 2 and Vertix 3",
    },
    "finger_millet": {"caption": "Finger millet", "codes": {"RES02": "FIMLT", "RES05": "FIML"}},
    "flax": {"caption": "Flax fibre", "codes": {"RES02": "FLAX", "RES05": "FLX"}},
    "fonio": {"caption": "Fonio", "codes": {"RES02": "FONIO", "RES05": "FONIO"}},
    "foxtail_millet": {"caption": "Foxtail millet", "codes": {"RES02": "FMLT", "RES05": "FML"}},
    "gram": {"caption": "Gram", "codes": {"RES02": "GRAM", "RES05": "GRM"}},
    "groundnut": {"caption": "Groundnut", "codes": {"RES02": "GRND", "RES05": "GRD", "RES06": "GRD", "RES07": "GRD"}, "description": "RES06 reports with shell"},
    "jatropha": {"caption": "Jatropha", "codes": {"RES02": "JATR", "RES05": "JTR"}},
    "macauba_palm": {
        "caption": "Macauba palm",
        "codes": {"RES02": "MCAU", "RES05": "MCA"},
        "subtypes": {
            "intercropping": {"codes": {"RES02": "MCAU2"}, "description": "Inter-cropping system"},
        },
        "description": "Single cropping; RES02 also has inter-cropping variant",
    },
    "maize": {
        "caption": "Maize",
        "codes": {"RES02": "MAIZ", "RES05": "MZE", "RES06": "MZE", "RES07": "MZE"},
        "subtypes": {
            "highland_tropics": {"codes": {"RES02": "HMZE"}, "description": "Highland tropics"},
            "lowland": {"codes": {"RES02": "LMZE"}, "description": "Lowland"},
            "temperate": {"codes": {"RES02": "TMZE"}, "description": "Temperate/sub-tropical"},
            "silage": {"codes": {"RES02": "MZSI", "RES05": "MZS"}, "description": "Silage maize"},
        },
        "description": "Best of highland, lowland, and temperate types",
    },
    "mango": {"caption": "Mango", "codes": {"RES02": "MANG", "RES05": "MNG"}},
    "millet": {"caption": "Millet", "codes": {"RES02": "MLLT", "RES06": "MLT", "RES07": "MLT"}, "description": "Aggregate millet — see also pearl_millet, finger_millet, foxtail_millet"},
    "miscanthus": {"caption": "Miscanthus", "codes": {"RES02": "MISC", "RES05": "MIS"}},
    "napier_grass": {"caption": "Napier grass", "codes": {"RES02": "NAPR", "RES05": "NAP"}},
    "oat": {"caption": "Oat", "codes": {"RES02": "OATS", "RES05": "OAT"}},
    "oil_palm": {"caption": "Oil palm", "codes": {"RES02": "OILP", "RES05": "OLP", "RES06": "OLP", "RES07": "OLP"}, "description": "RES06/RES07 report as oil palm fruit"},
    "okra": {"caption": "Okra", "codes": {"RES02": "OKRA", "RES05": "OKRA"}},
    "olive": {"caption": "Olive", "codes": {"RES02": "OLIV", "RES05": "OLV"}},
    "onion": {"caption": "Onion", "codes": {"RES02": "ONIO", "RES05": "ONI"}},
    "para_rubber": {"caption": "Para-rubber", "codes": {"RES02": "PRUB", "RES05": "RUB", "RES06": "RUB"}},
    "pasture_grasses": {"caption": "Pasture grasses", "codes": {"RES02": "GRAS", "RES05": "PST"}},
    "pasture_legumes": {"caption": "Pasture legumes", "codes": {"RES02": "GRLG"}, "description": "RES02 only"},
    "pearl_millet": {"caption": "Pearl millet", "codes": {"RES02": "PMLT", "RES05": "PML"}},
    "phaseolus_bean": {"caption": "Phaseolus bean", "codes": {"RES02": "BEAN", "RES05": "PHB"}},
    "pigeon_pea": {"caption": "Pigeon pea", "codes": {"RES02": "PIGP", "RES05": "PIG"}},
    "rapeseed": {
        "caption": "Rapeseed",
        "codes": {"RES02": "RAPE", "RES05": "RSD", "RES06": "RSD", "RES07": "RSD"},
        "subtypes": {
            "spring": {"codes": {"RES02": "SRAP"}, "description": "Spring rapeseed"},
            "winter": {"codes": {"RES02": "WRAP"}, "description": "Winter rapeseed"},
        },
        "description": "Best of spring and winter types",
    },
    "reed_canary_grass": {"caption": "Reed canary grass", "codes": {"RES02": "RCGR", "RES05": "RCG"}},
    "rice_wetland": {"caption": "Wetland rice", "codes": {"RES02": "RICW", "RES05": "RCW", "RES06": "RCW", "RES07": "RCW"}},
    "rye": {
        "caption": "Rye",
        "codes": {"RES02": "RYES", "RES05": "RYE"},
        "subtypes": {
            "spring": {"codes": {"RES02": "SRYE"}, "description": "Spring rye"},
            "winter": {"codes": {"RES02": "WRYE"}, "description": "Winter rye"},
        },
        "description": "Best of spring and winter types",
    },
    "sesame": {"caption": "Sesame", "codes": {"RES02": "SESA", "RES05": "SES", "RES06": "SES", "RES07": "SES"}},
    "solaris_tobacco": {"caption": "Solaris energy tobacco", "codes": {"RES02": "SOLA", "RES05": "SOL"}, "description": "Energy tobacco variant"},
    "sorghum": {
        "caption": "Sorghum",
        "codes": {"RES02": "SORG", "RES05": "SRG", "RES06": "SRG", "RES07": "SRG"},
        "subtypes": {
            "highland_tropics": {"codes": {"RES02": "HSRG"}, "description": "Highland tropics"},
            "lowland": {"codes": {"RES02": "LSRG"}, "description": "Lowland"},
            "temperate": {"codes": {"RES02": "TSRG"}, "description": "Temperate/sub-tropical"},
        },
        "description": "Best of highland, lowland, and temperate types. See also biomass_sorghum.",
    },
    "soybean": {"caption": "Soybean", "codes": {"RES02": "SOYB", "RES05": "SOY", "RES06": "SOY", "RES07": "SOY"}},
    "sugar_beet": {"caption": "Sugar beet", "codes": {"RES02": "SUGB", "RES05": "SUB", "RES06": "SUB", "RES07": "SUB"}, "description": "Yield in kg sugar/ha"},
    "sugar_cane": {"caption": "Sugar cane", "codes": {"RES02": "SUGC", "RES05": "SUC", "RES06": "SUC", "RES07": "SUC"}, "description": "Yield in kg sugar/ha"},
    "sunflower": {"caption": "Sunflower", "codes": {"RES02": "SUNF", "RES05": "SFL", "RES06": "SFL", "RES07": "SFL"}, "description": "RES06/RES07 report as sunflower seed"},
    "sweet_potato": {"caption": "Sweet potato", "codes": {"RES02": "SPOT", "RES05": "SPO"}, "description": "RES06/RES07 aggregate with white potato under POT"},
    "switchgrass": {"caption": "Switchgrass", "codes": {"RES02": "SWGR", "RES05": "SWG"}},
    "tannia": {"caption": "Tannia", "codes": {"RES02": "TANN", "RES05": "TANN"}, "description": "Xanthosoma sagittifolium"},
    "taro": {
        "caption": "Taro",
        "codes": {"RES05": "CYA"},
        "subtypes": {
            "dryland": {"codes": {"RES02": "TARODL", "RES05": "TAROD"}, "description": "Dryland taro (Colocasia esculenta)"},
            "wetland": {"codes": {"RES02": "TAROWL", "RES05": "TAROW"}, "description": "Wetland taro (Colocasia esculenta)"},
        },
        "description": "RES05 aggregate; RES02 splits into dryland and wetland",
    },
    "tea": {"caption": "Tea", "codes": {"RES02": "TEAS", "RES05": "TEA", "RES06": "TEA"}, "description": "Best of China, Assam, and hybrid types. RES06 includes mate leaves."},
    "tef": {"caption": "Tef", "codes": {"RES02": "TEFF", "RES05": "TEF"}},
    "tobacco": {"caption": "Tobacco", "codes": {"RES02": "TOBA", "RES05": "TOB", "RES06": "TOB", "RES07": "TOB"}, "description": "RES06/RES07 report as tobacco leaves. See also solaris_tobacco."},
    "tomato": {"caption": "Tomato", "codes": {"RES02": "TOMA", "RES05": "TOM", "RES06": "TOM"}},
    "triticale": {"caption": "Triticale", "codes": {"RES02": "TRIT", "RES05": "TRI"}},
    "watermelon": {"caption": "Watermelon", "codes": {"RES02": "WMEL", "RES05": "WMEL"}},
    "wheat": {
        "caption": "Wheat",
        "codes": {"RES02": "WHEA", "RES05": "WHE", "RES06": "WHE", "RES07": "WHE"},
        "subtypes": {
            "spring": {"codes": {"RES02": "SWHE"}, "description": "Spring wheat"},
            "winter": {"codes": {"RES02": "WWHE"}, "description": "Winter wheat (sub-tropical and tropical highland)"},
            "highland": {"codes": {"RES02": "HWHE"}, "description": "Highland wheat (tropics)"},
            "temperate": {"codes": {"RES02": "TWHE"}, "description": "Temperate/sub-tropical wheat"},
        },
        "description": "Best of all wheat types",
    },
    "white_potato": {"caption": "White potato", "codes": {"RES02": "WPOT", "RES05": "WPO"}, "description": "RES06/RES07 aggregate with sweet potato under POT"},
    "yam": {
        "caption": "Yam",
        "codes": {"RES02": "YAMS", "RES05": "YAM"},
        "subtypes": {
            "white": {"codes": {"RES02": "WYAM"}, "description": "White yam"},
            "greater": {"codes": {"RES02": "GYAM"}, "description": "Greater yam"},
            "yellow": {"codes": {"RES02": "YYAM"}, "description": "Yellow yam"},
        },
        "description": "Best of white, greater, and yellow yams",
    },
}

# RES06/RES07 aggregate crop groups — don't map 1:1 to suitability crops.
CROP_AGGREGATE_GROUPS = {
    "all_crops": {"codes": {"RES06": "ALL", "RES07": "GAP"}, "description": "All crops combined"},
    "major_crops": {"codes": {"RES06": "MAJ"}, "description": "Major crops combined"},
    "cereals": {"codes": {"RES06": "CER", "RES07": "GCE"}, "description": "All cereal crops"},
    "oil_crops": {"codes": {"RES06": "OIL", "RES07": "GOI"}, "description": "All oil crops"},
    "root_tuber_crops": {"codes": {"RES06": "RTS", "RES07": "GRT"}, "description": "Root and tuber crops"},
    "pulses": {"codes": {"RES06": "PLS"}, "description": "All pulse crops"},
    "fodder_crops": {"codes": {"RES06": "FDD"}, "description": "Fodder crops"},
    "fruits_nuts": {"codes": {"RES06": "FRT"}, "description": "Fruits and nuts"},
    "other_cereals": {"codes": {"RES06": "OCE", "RES07": "OCE"}, "description": "Oats, rye, buckwheat, and other minor grains"},
    "other_vegetables": {"codes": {"RES06": "OVG"}, "description": "All vegetables except tomato"},
    "olives_minor_oils": {"codes": {"RES06": "OOC"}, "description": "Olives and other minor oil crops"},
    "yams_minor_roots": {"codes": {"RES06": "ORT"}, "description": "Yams and other minor root crops"},
    "potato_combined": {"codes": {"RES06": "POT", "RES07": "POT"}, "description": "White potato and sweet potato combined"},
    "other_crops": {"codes": {"RES06": "NES"}, "description": "Mainly spices, fibre crops, and other crops not elsewhere included"},
}


# ──────────────────────────────────────────────────────────────────────
# 4. DIMENSIONS — API query parameters (non-crop)
# ──────────────────────────────────────────────────────────────────────

CLIMATE_MODELS = {
    "AGERA5":         {"caption": "AgERA5", "description": "Copernicus AgERA5 reanalysis. Used for historical periods (1981-2000, 2001-2020)."},
    "GFDL-ESM4":      {"caption": "GFDL-ESM4", "description": "NOAA Geophysical Fluid Dynamics Laboratory Earth System Model v4."},
    "IPSL-CM6A-LR":   {"caption": "IPSL-CM6A-LR", "description": "Institut Pierre-Simon Laplace Climate Model v6A, low resolution."},
    "MPI-ESM1-2-HR":  {"caption": "MPI-ESM1-2-HR", "description": "Max Planck Institute Earth System Model v1.2, high resolution."},
    "MRI-ESM2-0":     {"caption": "MRI-ESM2-0", "description": "Meteorological Research Institute Earth System Model v2.0."},
    "UKESM1-0-LL":    {"caption": "UKESM1-0-LL", "description": "UK Earth System Model v1.0, low-level configuration."},
    "ENSEMBLE":       {"caption": "Ensemble mean", "description": "Mean of all five CMIP6 GCMs above. Recommended default for future projections."},
}

PERIODS = {
    "HP8100": {"caption": "1981-2000", "type": "historical"},
    "HP0120": {"caption": "2001-2020", "type": "historical"},
    "FP2140": {"caption": "2021-2040", "type": "future"},
    "FP4160": {"caption": "2041-2060", "type": "future"},
    "FP6180": {"caption": "2061-2080", "type": "future"},
    "FP8100": {"caption": "2081-2100", "type": "future"},
}

SSP_SCENARIOS = {
    "HIST":   {"caption": "Historical", "description": "No SSP — used with historical periods HP8100 and HP0120."},
    "SSP126": {"caption": "SSP1-2.6", "description": "Sustainability pathway. Low emissions, warming ~1.8C by 2100."},
    "SSP370": {"caption": "SSP3-7.0", "description": "Regional rivalry pathway. High emissions, warming ~3.6C by 2100."},
    "SSP585": {"caption": "SSP5-8.5", "description": "Fossil-fueled development. Very high emissions, warming ~4.4C by 2100."},
}

INPUT_LEVELS = {
    "_note": "Used by RES02 (dimension WSIM-RES02) and RES05 (dimension WSIM-RES05). Codes are identical.",
    "HRLM": {"caption": "Rain-fed, high input", "water_supply": "rainfed", "management": "high"},
    "HILM": {"caption": "Irrigated, high input", "water_supply": "irrigated", "management": "high"},
    "LRLM": {"caption": "Rain-fed, low input", "water_supply": "rainfed", "management": "low"},
    "LILM": {"caption": "Irrigated, low input", "water_supply": "irrigated", "management": "low"},
}

WATER_SUPPLY = {
    "_note": "Used by RES06 actual production data (dimension WTS).",
    "WSR": {"caption": "Rain-fed"},
    "WSI": {"caption": "Irrigated"},
    "WST": {"caption": "Total"},
}

WATER_CONTENT = {
    "_note": "AWC of soil profile in mm/m. Used by RES01 agro-climatic datasets (dimension WTC). Suffix A = irrigated, B = rain-fed.",
    "015B": {"awc_mm_per_m": 15, "water_supply": "rainfed"},
    "050B": {"awc_mm_per_m": 50, "water_supply": "rainfed"},
    "075B": {"awc_mm_per_m": 75, "water_supply": "rainfed"},
    "100A": {"awc_mm_per_m": 100, "water_supply": "irrigated"},
    "100B": {"awc_mm_per_m": 100, "water_supply": "rainfed"},
    "125B": {"awc_mm_per_m": 125, "water_supply": "rainfed"},
    "150A": {"awc_mm_per_m": 150, "water_supply": "irrigated"},
    "150B": {"awc_mm_per_m": 150, "water_supply": "rainfed"},
    "175B": {"awc_mm_per_m": 175, "water_supply": "rainfed"},
    "200A": {"awc_mm_per_m": 200, "water_supply": "irrigated"},
    "200B": {"awc_mm_per_m": 200, "water_supply": "rainfed"},
}

MANAGEMENT_LEVELS = {
    "_note": "Used by SQX and SQ-IDX datasets (dimension IM-SQ).",
    "HIM": {"caption": "High input management", "description": "Improved varieties, adequate fertilization, pest control."},
    "LIM": {"caption": "Low input management", "description": "Traditional varieties, minimal external inputs."},
}

SOIL_QUALITIES = {
    "_note": "Seven GAEZ soil quality factors plus composite minimum. Rated 0-1 using HWSD v2.01 with maize as reference crop. Referenced by SQ-IDX classes.",
    "SQ0": {"caption": "Most limiting factor", "description": "Minimum of SQ1-SQ7. Identifies the single biggest soil bottleneck."},
    "SQ1": {"caption": "Nutrient availability", "description": "Based on soil organic carbon, pH, total exchangeable bases, soil texture."},
    "SQ2": {"caption": "Nutrient retention capacity", "description": "Based on CEC clay ratio, base saturation, pH, soil organic carbon."},
    "SQ3": {"caption": "Rooting conditions", "description": "Based on effective soil depth, soil volume, vertic properties."},
    "SQ4": {"caption": "Oxygen availability to roots", "description": "Based on drainage class and soil phases affecting aeration."},
    "SQ5": {"caption": "Salinity and sodicity", "description": "Based on electrical conductivity, exchangeable sodium percentage, soil phases."},
    "SQ6": {"caption": "Lime and gypsum", "description": "Based on calcium carbonate content, gypsum content."},
    "SQ7": {"caption": "Workability", "description": "Based on soil texture, effective soil depth, vertic properties, petric/ite phases."},
}

LAND_COVER_CLASSES = {
    "_note": "GAEZ v5 land cover inventory for 2020. Each class = percentage share of grid cell.",
    "LC01": {"caption": "Built-up land"},
    "LC02": {"caption": "Cropland"},
    "LC03": {"caption": "Grassland"},
    "LC04": {"caption": "Tree-covered"},
    "LC05": {"caption": "Shrub-covered"},
    "LC06": {"caption": "Shrub/herbaceous, regularly flooded"},
    "LC07": {"caption": "Tree-covered, flooded saline"},
    "LC08": {"caption": "Lichen and mosses"},
    "LC09": {"caption": "Bare or sparsely vegetated land"},
    "LC10": {"caption": "Permanent snow/glacier"},
    "LC11": {"caption": "Water"},
    "LC12": {"caption": "Cropland, irrigated"},
}


# ──────────────────────────────────────────────────────────────────────
# Helpers
# ──────────────────────────────────────────────────────────────────────

DIMENSION_PROFILES = {
    "historical_only": {
        "periods": ["HP8100", "HP0120"],
        "climate_models": ["AGERA5"],
        "ssp_scenarios": ["HIST"],
    },
    "historical+future": {
        "periods": ["HP8100", "HP0120", "FP2140", "FP4160", "FP6180", "FP8100"],
        "climate_models_historical": ["AGERA5"],
        "climate_models_future": list(CLIMATE_MODELS.keys()),
        "ssp_scenarios_historical": ["HIST"],
        "ssp_scenarios_future": ["SSP126", "SSP370", "SSP585"],
    },
    "static": {
        "periods": [],
        "climate_models": [],
        "ssp_scenarios": [],
    },
}


def get_datasets_by_category(category):
    """Return all map_codes belonging to a category."""
    return [k for k, v in METADATA_TEMPLATES.items() if v.get("category") == category]


def get_dimension_profile(map_code):
    """Return the full dimension profile for a map_code."""
    profile_name = METADATA_TEMPLATES[map_code]["dimension_profile"]
    return DIMENSION_PROFILES[profile_name]


def resolve_sq_idx_class(class_value):
    """Convert SQ-IDX pixel value to soil quality description."""
    key = f"SQ{class_value}"
    return SOIL_QUALITIES.get(key, {}).get("caption", f"Unknown SQ{class_value}")

"""Reference metadata templates for GAEZ crops, layers, and code mappings."""
